"""Add cookbook_user Association Table

Revision ID: 210a57de34aa
Revises: f432eb8325ae
Create Date: 2023-03-09 23:00:51.879148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210a57de34aa'
down_revision = 'f432eb8325ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cookbook_users',
    sa.Column('cookbook_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cookbook_id'], ['cookbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cookbook_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookbook_users')
    op.drop_table('users')
    # ### end Alembic commands ###
