"""Added new columns to tables

Revision ID: 992620bc2890
Revises: db3294709296
Create Date: 2023-03-07 19:55:49.771035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992620bc2890'
down_revision = 'db3294709296'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookbooks', sa.Column('author_id', sa.Integer(), nullable=True))
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    op.add_column('recipes', sa.Column('book_id', sa.Integer(), nullable=True))
    sa.ForeignKeyConstraint(['book_id'], ['cookbooks.id'], )

    # op.create_foreign_key(None, 'recipes', 'cookbooks', ['book_id'], ['id'])
    # op.create_foreign_key('fk_recipes_cookbooks', 'recipes', 'cookbooks', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'book_id')
    op.drop_constraint(None, 'cookbooks', type_='foreignkey')
    op.drop_column('cookbooks', 'author_id')
    # ### end Alembic commands ###
